spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      settings:
        web-admin-password: sa
      path: /h2
  sql:
    init:
      encoding: UTF-8

#server:
#  port: 9099

#前端網址
viewUrl:
  https://loxa5210.github.io/,http://localhost:8080

